trigger:
  batch: true

variables:
  testConfiguration: 'Debug'

resources:
  repositories:
  - repository: wallet
    type: github
    name: zkSNACKs/WalletWasabi
    endpoint: github.com_molnard
    ref: master

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - checkout: self
    path: WasabiDeploy
  - checkout: wallet
    path: WasabiDeploy.Temp\WalletWasabi
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3'
    inputs:
      version: 3.1.x
  - task: DotNetCoreCLI@2
    inputs:
      command: 'run'
      projects: '**/WasabiDeploy.Publish.csproj'
      arguments: '--configuration Debug'
